CREATE TABLE BANKINFO (
	    BANK_NO VARCHAR2(20) NOT NULL, -- 계좌번호
	    BANK_NAME VARCHAR2(50) NOT NULL,  -- 은행명
	    BANK_USER_NAME VARCHAR2(30) NOT NULL, -- 예금주명
	    BANK_DATE DATE,  -- 날짜
	    CONSTRAINT PK_BANKINFO PRIMARY KEY (BANK_NO)
);
